### ISSUE TITLE
Support for R Kernel - Feature Request

### ISSUE THREAD

**Issue by sshtomar** [squaredtechnologies/vizly-notebook#10]
Hi,

It's easy to set up the R kernel in a Jupyter Notebook: https://irkernel.github.io/
Would be very helpful if this can be done.

**Comment by alishobeiri** [comment]
Hi Shubham, it was a pleasure speaking with you today. For the R kernel, I'll wait for you to test it and get back to me about  the experience. As far as I know, it should be able to support it out of the box, though the code highlighting will likely need to be changed / updated.

**Comment by sshtomar** [comment]
Hi @alishobeiri,

Yes, the R kernel works out of the box.

Steps to install R kernel:
1. Open R console
2. Run `install.packages('IRkernel')`
3. Run `IRkernel::installspec()`

**Comment by alishobeiri** [comment]
Sounds great, will close for now
