### ISSUE TITLE
Errors about Keeping Running

### ISSUE THREAD

**Issue by mamingsuper** [squaredtechnologies/vizly-notebook#11]
thank u so much for developing this amazing tool.

I encounter with a problem that it has been keeping fixing same error and cannot stop automactically.

**Comment by samisahn** [comment]
Thank you for the kind words!

Would you mind sharing more details around what went wrong? If you have a photo or a short video, that'd be great. Thanks!

**Comment by alishobeiri** [comment]
Addressed in this [commit](https://github.com/squaredtechnologies/thread/commit/7191c573d66557dcfe84aa6044e65f8537028c4e). I believe the issue was related to an off by one error, should be available in 0.1.8 if you wouldn't mind giving it a try!
