### ISSUE TITLE
 Integrate  with Langfuse - New Request

### ISSUE THREAD

**Issue by jackie19** [squaredtechnologies/vizly-notebook#14]
hi, 
Is it easy to integrate with Lanfuse ? [https://langfuse.com/docs/get-started](https://langfuse.com/docs/get-started)
It will be very important for us to build an AI app internally, thanks.

**Comment by alishobeiri** [comment]
Hi Jackie, 

Langfuse has now been added, take a look and let me know what you think! https://github.com/squaredtechnologies/thread/commit/371565f3d50252ba25fb8c316c77899e1cb7d50e

If you have some time, would love to learn what type of application you are hoping to build internally. Happy to help if possible. You can reach me on my calendar [here](https://cal.com/ali-shobeiri/30min).
