### ISSUE TITLE
Unable to use as a Python package

### ISSUE THREAD

**Issue by sshtomar** [squaredtechnologies/vizly-notebook#15]
Hi,

I installed thread-dev using the following commands:

```
python3 -m venv .env
source .env/bin/activate
pip install thread-dev
```
Installation worked. But, when I run `thread` or `jupyter thread`, the jupyter notebook window says: File index.html not found

<img width="1461" alt="image" src="https://github.com/squaredtechnologies/thread/assets/5631503/1d2c6110-f77b-41d8-856b-65fadec2fcad">

**Comment by alishobeiri** [comment]
Could you provide some more information on what package version you are working with, or what operating system? I am not able to replicate the issue you are seeing

**Comment by alishobeiri** [comment]
Closing as can't reproduce and have not heard anything back from filer
