### ISSUE TITLE
It crashes My Jupyter Notebook

### ISSUE THREAD

**Issue by Ad163** [squaredtechnologies/vizly-notebook#18]
I think that you should add a video working someone through the installation process. My Jupiter Notebook Server was corrupted after running the command pip install thread-dev

**Comment by alishobeiri** [comment]
Hey @Ad163, thanks so much for the report. Do you mind sharing more information? 

How are you determining it was corrupted? 

Could you share some errors of what you are seeing or what you are having trouble with?

**Comment by alishobeiri** [comment]
Closing as haven't heard back from filer
