### ISSUE TITLE
Error while installing thread on jupyter notebook

### ISSUE THREAD

**Issue by Bkarine** [squaredtechnologies/vizly-notebook#19]
Hi, I tried to install Thread on Jupyter Notebook. The installation seemed to be fine but when it write "jupyter thread" or "thread", an error shows up "SyntaxError: invalid syntax". Please see screenshots attached. I´m on Mac. Thanks.
![image](https://github.com/squaredtechnologies/thread/assets/147745812/c6e0a435-7c6a-4113-933a-1980a4a6fa8b)

**Comment by alishobeiri** [comment]
Hi @Bkarine, 

To run thread from your Jupyter Notebook, please run `!jupyter thread` 

With the `!` at the start.

If you want to run thread on it's on outside of a Jupyter Notebook, please run:
`jupyter thread` in a terminal instead

**Comment by alishobeiri** [comment]
Closing as this issue should be resolved with the solution mentioned above

**Comment by Bkarine** [comment]
Thanks!
