### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by namin** [squaredtechnologies/vizly-notebook#2]
I had to do `yarn add ignore-loader` as an extra step to avoid a module not found error.

On http://localhost:3000/thread, I get the error:
```
Next.js (14.2.3)
Unhandled Runtime Error
TypeError: (0 , _motion_proxy_mjs__WEBPACK_IMPORTED_MODULE_4__.createMotionProxy) is not a function
```
but I could ignore it.

I am unable to create a new notebook. I see the message:
```
New notebook
No kernels could be found
```

Thanks!

**Comment by alishobeiri** [comment]
Thanks a lot Namin, just addressed this in the latest commits!

https://github.com/squaredtechnologies/thread/commit/57a4a97649182055beec16e8f5a5174e5ee86579
https://github.com/squaredtechnologies/thread/commit/79aa9d84d56e5abc5fa1c578aae8faec640044f4

**Comment by jackie19** [comment]
I have another issue when I looked in to network from dev-tools
![image](https://github.com/squaredtechnologies/thread/assets/2063608/70e787dc-6e44-44ab-a30e-1c73c94373cb)

**Comment by jackie19** [comment]
fixed. have to copy token from jupyter-server.

**Comment by jackie19** [comment]
fixed. have to copy tokens from jupyter-server.

**Comment by alishobeiri** [comment]
Hi Jackie,

Yes the easiest way you can avoid the token requirement is if you use `sh ./ run_dev.sh ( http://run_dev.sh/ ) ` that will start a development server that doesn't require a token.

Let me know if can help with anything in the future! Please also feel free to join the Discord if you are interested: https://discord.gg/2gAWw9KV

Best regards,

Ali Shobeiri
