### ISSUE TITLE
ollama not working

### ISSUE THREAD

**Issue by azharz4u** [squaredtechnologies/vizly-notebook#22]
![image](https://github.com/squaredtechnologies/thread/assets/14932858/6b3f2603-6833-4ee1-ae0e-ab35fcb2c726)
when i selected ollama then why it is going for OpenAI API requests

**Comment by alishobeiri** [comment]
Thanks for the report, let me take a look. Likely it is a logic error on our side

**Comment by alishobeiri** [comment]
Believe this fixes it: https://github.com/squaredtechnologies/thread/pull/23

**Comment by alishobeiri** [comment]
@azharz4u can you please try with `thread-dev==0.1.15`?

**Comment by alishobeiri** [comment]
Verified it has been fixed on `0.1.15` please reopen if you are still seeing the issue
