### ISSUE TITLE
support specifying  a particular model in the openai setting.

### ISSUE THREAD

**Issue by lightzhan-intellif** [squaredtechnologies/vizly-notebook#25]
When we use service from an openai api compatible provider, we may need to specify a custom model instead of the default gpt-4o. Or maybe we want to try out other models of openai sometimes. Now we can not do this. I think it will help much if supported.

**Comment by lightzhan-intellif** [comment]
Basically, It will be better if we support setting temperature/top_k/top_p etc.

**Comment by alishobeiri** [comment]
Hi Lightzhan, the ability to select multiple models is supported in 0.1.21, would love for you to give it a try and share your feedback!

**Comment by alishobeiri** [comment]
Added this to track the ability to add model parameters too https://github.com/squaredtechnologies/thread/issues/30
