### ISSUE TITLE
Add support for Anthropic Claude 3 family

### ISSUE THREAD

**Issue by robertritz** [squaredtechnologies/vizly-notebook#27]
It would be great to be able to add the Claude 3 (particularly the new Sonnet 3.5 model). It's faster and seemingly better than GPT-4o.

**Comment by guidov** [comment]
Groq would be useful here too. More flexibility with the API URL would be a bonus. Something like what they do here: https://github.com/open-webui/open-webui

Appreciate the work on this project , it looks like it has a lot of potential :)

**Comment by Playerrrrr** [comment]
if the maintainer is not willing to, someone should do it via fork?

**Comment by BardiaKh** [comment]
I am not a maintainer of the package, but am working towards that goal. Will soon create a PR to add Anthropic models, including the latest 3.5 Sonnet.

**Comment by alishobeiri** [comment]
Hi folks, we are not ignoring this issue, in fact we are making progress towards some of the preliminary steps that are required to get this ready to ship where @BardiaKh has led a lot of the effort. Will make sure to try to keep you more updated on the issue in the future.

**Comment by alishobeiri** [comment]
Thank you to @BardiaKh, this will be released in 0.1.21
