### ISSUE TITLE
Multiple running timers

### ISSUE THREAD

**Issue by BardiaKh** [squaredtechnologies/vizly-notebook#31]
Thank you for adding the timer feature! It is very useful. I think there is a small issue in the implementation that starts the timer when the run button is clicked not actually when the run starts:

<img width="831" alt="image" src="https://github.com/squaredtechnologies/thread/assets/13269112/9001e5cf-959b-4165-9afe-6f8514ad4027">

I can help by prepping an initial PR if you guide me where to start.

**Comment by alishobeiri** [comment]
Thanks a lot, I will address that!

**Comment by alishobeiri** [comment]
Addressed in v0.1.22!
