### ISSUE TITLE
Chat does not generate response when using Anthropic API Key

### ISSUE THREAD

**Issue by ldabas** [squaredtechnologies/vizly-notebook#34]

**Comment by alishobeiri** [comment]
Hi Lakshit, 

Thanks for the issue, I am taking a look at this now. Can you tell me what pip version of `vizly-notebook` you are using?

**Comment by ldabas** [comment]
version (0.1.26)

**Comment by alishobeiri** [comment]
Thanks a lot, there seems to be a CORS issue coming from the Anthropic end. I am trying to see if there is a way to get around it

The easiest way to is to run the queries non-locally, ie run them through the proxy server. I am trying to find a resolution for this at the moment

**Comment by ldabas** [comment]
Could you please add some more documentation for setting up the proxy server? Thanks.
btw, great product, keep building :))

**Comment by alishobeiri** [comment]
Thanks a lot, if you got some time, would love to learn more about what you are using `vizly-notebook` for! 

The proxy server has a default address that I recommend using (`https://thread-41s7.onrender.com`) so you don't need to deal with setting one up for yourself. If you want to run your own proxy server, you can run the following commands:
```
cd proxy
yarn build:prod
yarn start
```

On whatever service you are hoping to run things on

**Comment by alishobeiri** [comment]
This is the issue on Anthropic's API: https://github.com/anthropics/anthropic-sdk-typescript/issues/219
