### ISSUE TITLE
Feature Request: Make Chat Panel Resizable Horizontally

### ISSUE THREAD

**Issue by bookofbash** [squaredtechnologies/vizly-notebook#6]
**Is your feature request related to a problem? Please describe.**
The current chat panel is fixed in width, which limits flexibility for users with different screen sizes and preferences. Users with larger screens might find the panel too narrow, while users with smaller screens might prefer a more compact interface.

**Describe the solution you'd like**
I would like the chat panel to be resizable horizontally. This would allow users to adjust the panel's width according to their preferences and screen sizes. A drag-able resizer handle on the edge of the chat panel would be ideal for this purpose.

**Describe alternatives you've considered**
An alternative could be providing a few preset width options for the chat panel that users can select from a settings menu. However, a drag-able resizer would offer more flexibility and a better user experience.

**Comment by samisahn** [comment]
Thanks for the feature request! Just addressed this in the latest commit ([fa95b7d](https://github.com/squaredtechnologies/thread/commit/fa95b7ddf7517dc32a7ce14de567a0cc4cc2dd4e)).

Here's a video after the change, demonstrating the adjustable panel width and persisted settings after refresh (as the width setting is saved in local storage):

https://github.com/squaredtechnologies/thread/assets/26368245/ee1089ec-b3c5-4e7a-b786-a1ded1161902
