### ISSUE TITLE
erdantic's chart can't display

### ISSUE THREAD

**Issue by HaveF** [squaredtechnologies/vizly-notebook#8]
Hi, it looks very nice! 

Thanks!
Just a quick test, find a bug. For the lib below, it can't display erdantic's chart.
[Usage Example: Pydantic - erdantic](https://erdantic.drivendata.org/stable/examples/pydantic/#using-the-python-library)

![image](https://github.com/squaredtechnologies/thread/assets/54462/f41dad85-93e4-4907-9337-c817e1e1fc15)

**Comment by alishobeiri** [comment]
Thanks a lot, will take a look at this, appreciate the feedback!

**Comment by alishobeiri** [comment]
I have been trying to look at this and every time I am defeated by:
```
Failed to build pygraphviz
ERROR: Could not build wheels for pygraphviz, which is required to install pyproject.toml-based projects
```

Will need to dig deeper I think

**Comment by alishobeiri** [comment]
<img width="1161" alt="image" src="https://github.com/squaredtechnologies/thread/assets/18422723/364eb232-7253-49d4-b3e6-e0b93b5f28b2">

Progress has been made

**Comment by alishobeiri** [comment]
Believe this has been fixed with: https://github.com/squaredtechnologies/thread/commit/bda38f1db4acd24a488e3cc1b470dcecfb60978f 

Thanks a lot for the issue!

**Comment by HaveF** [comment]
@alishobeiri nice. thanks!

To be honest, I have tried to use AI-related plugins in Jupyter, but the user experience was terrible.
I saw your news on HN and came to experiment. I feel that this is the right way to use AI in Jupyter.
And you used React, I believe you can make use of a lot of existing ecosystems in React. Awesome.

In addition, I looked at your roadmap, and suddenly thought that if you have a set of methods to use React/Python to make plugins and then put them into your environment in the future, it would be great!

I hope you develop well! I believe you have so [many possibilities](https://observablehq.com/pricing).

**Comment by alishobeiri** [comment]
Hi HaveF, thanks a lot. Curious to learn, for the React/Python plugin, what is the primary use case you have in mind?

**Comment by HaveF** [comment]
@alishobeiri Dashboard? Similar to your `Publish notebooks as shareable webapps` in your roadmap. It can leverage numerous React UI libraries.
And UI support for tools, like, my most favorite notebook tool -- [nbdev](https://github.com/fastai/nbdev).

**Comment by HaveF** [comment]
Also, considering this is a tool under jupyter, I was wondering. Is it necessary to repeatedly implement some existing [extensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/), such as `Table of Contents` and so on?(like `Add support for Jupyter Widgets` in roadmap? do we really need this or want something more? I have no idea.) Although there are many extensions that are no longer required in `jupyter lab`. Or just leave a plugin workflow for others to create what they need.

I think we may need to carefully consider what makes this tool different from other tools. After all, resources are limited.
